// Generated by https://quicktype.io

export interface Data {
    ciudadanos: Ciudadano[];
}

export interface Ciudadano {
    id?:            number;
    nombre?:        string;
    email?:         string;
    comuna?:        number;
    zona_votacion?: number;
}
